# Generated by Django 4.0.4 on 2022-05-22 05:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0002_productvariation'),
        ('cart', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='cartitems',
            name='product_variation',
            field=models.ManyToManyField(blank=True, to='store.productvariation'),
        ),
    ]
