# Generated by Django 4.0.4 on 2022-06-01 05:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0002_productvariation'),
        ('orders', '0005_alter_payment_payment_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orderproduct',
            name='product_variation',
        ),
        migrations.AddField(
            model_name='orderproduct',
            name='product_variation',
            field=models.ManyToManyField(blank=True, to='store.productvariation'),
        ),
    ]
